# Generated by Django 4.1.7 on 2023-04-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('road', models.CharField(max_length=70)),
                ('number', models.PositiveIntegerField(default=1)),
                ('borhood', models.CharField(max_length=100)),
                ('CEP', models.CharField(max_length=9)),
                ('city', models.CharField(max_length=70)),
                ('state', models.CharField(max_length=70)),
            ],
        ),
    ]
