# Generated by Django 4.1.7 on 2023-04-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='image',
            field=models.ImageField(default='', upload_to='shelters/%Y/%m/%d/', blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelter',
            name='phone',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='CEP',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='borhood',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='number',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='road',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
