# Generated by Django 4.1.7 on 2023-04-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_shelter_image_shelter_phone_alter_shelter_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='number',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
