# Generated by Django 4.1.7 on 2023-04-17 18:52

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shelter', '0004_alter_shelter_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelter',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='shelter',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='CEP',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='id',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='number',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='road',
        ),
        migrations.AddField(
            model_name='shelter',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
