version: '3.9'

services:
  postgres:
    image: postgres
    container_name: 'data_base'
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB

  pg_admin:
    image: dpage/pgadmin4
    container_name: pg_admin
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD    
    depends_on:
      - postgres
    ports:
      - "5000:80"
