# Generated by Django 5.1.1 on 2024-09-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='18-09-2024')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='pet/%Y/%m/%d/')),
                ('age', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=15)),
                ('characteristics', models.CharField(max_length=25)),
                ('adopted', models.BooleanField(default=False)),
            ],
        ),
    ]
