# Generated by Django 4.1.7 on 2023-04-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(default='', upload_to='pet/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
