# Generated by Django 4.1.7 on 2023-04-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, upload_to='pet/%Y/%m/%d/'),
        ),
    ]
