# Generated by Django 4.1.7 on 2023-04-14 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
        ('pet', '0004_adocao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adocao',
            new_name='Adoption',
        ),
    ]
