# Generated by Django 4.1.7 on 2023-04-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_rename_adocao_adoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='date',
            field=models.DateField(default='16-04-2023'),
        ),
    ]
