# Generated by Django 4.1.7 on 2023-04-17 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_alter_adoption_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='adopted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='date',
            field=models.DateField(default='17-04-2023'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pet.pet'),
        ),
    ]
